### ISSUE TITLE
Не выкидывается исключение вида IllegalArgumentException, если максимальный баланс отрицательный

### ISSUE THREAD

**Issue by NadezhdaPetushkova** [PupiYakiSan/javaqa-team-diplom-2#11]
# Описание
В требованиях указано, что если параметры некорректны, то должно выкидываться исключения вида IllegalArgumentException. Максимальный баланс не может быть отрицательный.

# Локализация дефекта

https://github.com/PupiYakiSan/javaqa-team-diplom-2/blob/e738ba152e8ab73760a87aac2a109dee10d5a03e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/PupiYakiSan/javaqa-team-diplom-2) в IDEA
2. Создать объект класса SavingAccount с отрицательным максимальным балансом
4. Запустить программу
5. Посмотреть вывод консоли

*Ожидаемый результат:* Выбрасывается исключение IllegalArgumentException, так как максимальный баланс отрицательный.
*Фактический результат:* Не выбрасывается исключение IllegalArgumentException.

# Тест
По шагам воспроизведения реализован тест https://github.com/PupiYakiSan/javaqa-team-diplom-2/blob/e738ba152e8ab73760a87aac2a109dee10d5a03e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L142

# Скриншот
![image](https://github.com/PupiYakiSan/javaqa-team-diplom-2/assets/128499978/fa6ed8b6-7530-4c50-8ed9-d0bac95ef2ff)

# Окружение
**Операционная система:**  Windows 11
**IDE:** IntelliJ IDEA 2023.1 (Community Edition)
**Java:** OpenJDK11

**Comment by PupiYakiSan** [comment]
Учтено
