### ISSUE TITLE
В методе Pay после совершения покупки баланс становится отрицательным

### ISSUE THREAD

**Issue by NadezhdaPetushkova** [PupiYakiSan/javaqa-team-diplom-2#15]
# Описание
В требованиях сказано: "Если операция может привести к некорректному состоянию счёта (например, баланс может уйти в минус), то операция должна завершиться вернув false и ничего не поменяв на счёте." Сумма покупки превышает баланс, после расчета баланс становится отрицательным. 
 
# Локализация дефекта

https://github.com/PupiYakiSan/javaqa-team-diplom-2/blob/e738ba152e8ab73760a87aac2a109dee10d5a03e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L44

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/PupiYakiSan/javaqa-team-diplom-2) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 2_000, минимальным балансом 500, максимальным балансом 10_000 и процентной ставкой 5
3. Вызвать метод pay с суммой покупки 2500
4. Запустить программу
5. Посмотреть вывод консоли

*Ожидаемый результат:* Метод pay должен вернуть false, и баланс на счете должен остаться равным 2000.
*Фактический результат:* Метод pay возвращает false, но баланс становится равным -500.

# Тест
По шагам воспроизведения реализован тест https://github.com/PupiYakiSan/javaqa-team-diplom-2/blob/e738ba152e8ab73760a87aac2a109dee10d5a03e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L238

# Скриншот
![image](https://github.com/PupiYakiSan/javaqa-team-diplom-2/assets/128499978/3b705768-232b-4286-8427-d5a5dfc30a31)

# Окружение
**Операционная система:**  Windows 11
**IDE:** IntelliJ IDEA 2023.1 (Community Edition)
**Java:** OpenJDK11

**Comment by PupiYakiSan** [comment]
Учтено
