### ISSUE TITLE
В методе add при пополнении счета неверно рассчитывает итоговый баланс

### ISSUE THREAD

**Issue by NadezhdaPetushkova** [PupiYakiSan/javaqa-team-diplom-2#17]
# Описание
В методе add при пополнении счета неверно рассчитывает итоговый баланс, показывает сумму равную пополнению без учета начального баланса. 
 
# Локализация дефекта

https://github.com/PupiYakiSan/javaqa-team-diplom-2/blob/e738ba152e8ab73760a87aac2a109dee10d5a03e/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/PupiYakiSan/javaqa-team-diplom-2) в IDEA
2. Создать объект класса SavingAccount с начальным балансом 2_000 и максимальным балансом 10_000
3. Вызвать метод add с параметром amount равным 3_000
4. Проверить значение баланса после выполнения метода add

*Ожидаемый результат:* Итоговый баланс равен сумме начального баланса и пополнения, то есть 5000. 
*Фактический результат:* После пополнения итоговый баланс равен только сумме пополнения, то есть 3000. 

# Тест
По шагам воспроизведения реализован тест https://github.com/PupiYakiSan/javaqa-team-diplom-2/blob/e738ba152e8ab73760a87aac2a109dee10d5a03e/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

# Скриншот
![image](https://github.com/PupiYakiSan/javaqa-team-diplom-2/assets/128499978/66e725a0-a66e-4c33-8f4a-e89b059253af)

# Окружение
**Операционная система:**  Windows 11
**IDE:** IntelliJ IDEA 2023.1 (Community Edition)
**Java:** OpenJDK11

**Comment by PupiYakiSan** [comment]
Учтено
